version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: frontend
    ports:
      - "4600:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge