FROM node:18 AS build

WORKDIR /app
COPY front-angular/package*.json ./
RUN npm install
COPY front-angular/ ./
RUN npm run build -- --configuration production

FROM nginx:stable-alpine

# Copia seu build para o diretório padrão do Nginx
COPY --from=build /app/dist/front-angular /usr/share/nginx/html

# Copia sua configuração customizada
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 4600
CMD ["nginx", "-g", "daemon off;"]
