version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "9090:9090"
    volumes:
      - ./back-spring/controle-estoque/.env:/app/.env
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: frontend
    ports:
      - "4600:80"
    depends_on:
      - backend
    networks:
      - app-network
networks:
  app-network:
    driver: bridge